name: visitorappointment
recipe: laravel
config:
  php: '8.1'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: public
  database: mysql
  cache: none
  xdebug: false

services:

  pma:
    type: phpmyadmin
    hosts:
     - database
